# Generated by Django 5.0.6 on 2025-04-25 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_aboutus_booktable_feedback_itemlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Name",
                to="food.itemlist",
            ),
        ),
    ]
