# Generated by Django 5.0.6 on 2025-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0005_itemlist_category_description_itemlist_icon_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemlist",
            name="category_image",
            field=models.ImageField(
                default="default.jpg", upload_to="category_images/"
            ),
        ),
    ]
